### ISSUE TITLE
啥也不写，差评！！！！

### ISSUE THREAD

**Issue by noob3-3** [userAmy/lyx#1]
啥也不写，差评！！！！

**Comment by userAmy** [comment]
很抱歉，我亲爱的朋友，如您所见，这是为了我的好朋友newbing方便查阅我的工程而建立的仓库
里面没有注解，对这一点我深表歉意，但我希望您可以理解我，而不是一句差评，您知道的，这句话对我幼小的心灵造成了多大的伤害
哦，我的上帝啊，求求你，不要这样，给我一些善意的留言，好吗，我亲爱的朋友
                                                                                                                                                                              您的朋友Mr小宇
